<a href="https://colab.research.google.com/github/Codeginner/machineLearning-task/blob/main/UAS/PyTorch/Chapter%2000/Code_Chapter_00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Nama: Gilman Muslih Z

NIM: 1103201075

Codes Chapter 00 - Fundamental

## Import PyTorch

> Sebelum menggunakan framework PyTorch ke dalam project yang ingin kita buat, pertama yang harus dilakukan adalah meng-import library PyTorch serta mengecek versi PyTorch yang digunakan


In [ ]:
import torch
torch.__version__

'2.1.0+cu121'

Library PyTorch berhasil di-import dan seperti yang dilihat pada output kode di atas, versi PyTorch yang digunakan adalah 2.1.0+cu121 di mana pada petunjuk yang terdapat pada modul PyTorch ini dikatakan ketika versi PyTorch yang digunakan lebih besar dari 1.10.0+ akan terdapat beberapa perbedaan.

### Membuat tensor

> Untuk membuat tensor, pertama yang harus diketahui adalah scalar. Membuat scalar dapat memberikan fleksibilitas dalam mengelola data di PyTorch. Tensor skalar merupakan dasar untuk membangun struktur data yang lebih kompleks seperti vektor, matriks, dan tensor multidimensi lainnya.

In [ ]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

Dengan output yang dihasilkan, kita telah berhasil membuat tensor skalar dengan nilai 7 menggunakan PyTorch. Output tensor(7) menandakan meskipun scalar adalah sebuah angka tunggal, scalar merupakan tipe torch.Tensor. Kita bisa memeriksa dimensi dari sebuah tensor menggunakan atribut `ndim`.

In [ ]:
scalar.ndim

0

0 memberikan informasi tentang seberapa banyak dimensi yang dimiliki oleh tensor, dan dalam konteks tensor skalar, dimensinya adalah 0 karena hanya ada satu elemen tanpa dimensi tambahan.

Bagaimana jika kita ingin mengambil angka dari tensor. Misalnya, mengubahnya dari torch.Tensor menjadi bilangan bulat Python.

Untuk melakukannya kita dapat menggunakan metode item().

In [ ]:
# Dapatkan angka Python dalam sebuah tensor (hanya bekerja dengan tensor satu elemen)
scalar.item()

7

Dalam kode tersebut, `scalar.item()` digunakan untuk mengambil nilai skalar yang terkandung dalam tensor. Karena tensor skalar hanya memiliki satu elemen, panggilan fungsi `item()` mengembalikan nilai aktual dari tensor tersebut. Dalam hal ini, nilai dari tensor skalar yang telah dibuat sebelumnya adalah 7, sehingga output dari `scalar.item()` adalah 7. Fungsi ini berguna ketika kita perlu mengakses nilai dari tensor skalar secara langsung sebagai bilangan Python biasa, bukan sebagai objek tensor PyTorch.

Vector merupakan tensor 1 dimensi akan tetapi dapat menyimpan banyak angka. Misalnya, Anda dapat memiliki vektor [3, 2] untuk mendeskripsikan [kamar tidur, kamar mandi] di rumah Anda. Atau Anda dapat memiliki [3, 2, 2] untuk mendeskripsikan [kamar tidur, kamar mandi, tempat parkir mobil] di rumah Anda. Hal yang penting di sini adalah bahwa vektor bersifat fleksibel dalam merepresentasikan apa yang dapat direpresentasikannya (sama halnya dengan tensor).

In [ ]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

Baris pertama, `vector = torch.tensor([7, 7])`, membuat sebuah tensor vektor dengan dua elemen, yaitu 7 dan 7. Vektor ini dapat dianggap sebagai larik satu dimensi atau himpunan nilai yang disusun dalam urutan tertentu.

Selanjutnya, memeriksa dimensi dari vektor yang telah dibuat sebelumnya

In [ ]:
# cek dimensi dari vektor yang telah dibuat sebelumnya
vector.ndim

1

Dari output di atas, vektor berisi dua angka tetapi hanya memiliki satu dimensi. Kita dapat mengetahui jumlah dimensi yang dimiliki tensor di PyTorch dari jumlah tanda kurung siku di bagian luar ([) dan hanya perlu menghitung satu sisi saja.

Berapa banyak tanda kurung siku yang dimiliki vektor?

Konsep penting lainnya untuk tensor adalah atribut bentuknya. Bentuknya dapat memberi tahu bagaimana elemen-elemen di dalamnya disusun.


Untuk mengetahui bentuk vektor, dapat menggunakan kode di bawah ini

In [ ]:
# cek bentuk vektor
vector.shape

torch.Size([2])

Kode di atas menghasilkan `torch.Size([2])` yang berarti vektor kita memiliki bentuk `[2]`. Hal ini dikarenakan dua elemen yang kita tempatkan di dalam kurung siku (`[7, 7]`).

Selanjutnya **matrix**.

Matriks sering digunakan dalam berbagai aplikasi, termasuk transformasi linear, image processing, dan pemodelan sistem linier dalam konteks data science dan machine learning. Dengan menggunakan PyTorch, kita dapat dengan mudah membuat, memanipulasi, dan melakukan operasi matematis pada matriks-matriks ini.

In [ ]:
# membuat Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

matriks memberikan fleksibilitas yang sama seperti vektor, tetapi dengan dimensi tambahan yang memungkinkan representasi data yang lebih kompleks.

Selanjutnya mengecek dimensi dari matriks yang telah dibuat sebelumnya

In [ ]:
# memeriksa dimensi dari MATRIX
MATRIX.ndim

2

Output di atas menampilkan bahwa `MATRIX` memiliki 2 dimensi sedangkan kalau kita mengecek bentuk dari `MATRIX` itu sendiri?


In [ ]:
# cek bentuk dari MATRIX
MATRIX.shape

torch.Size([2, 2])

Output yang didapatkan adalah `torch.Size([2, 2])` karena matriks yang telah dibuat sebelumnya memiliki kedalaman dua elemen dan lebar dua elemen.

"dimension" atau "dimensi" merujuk pada jumlah sumbu atau tingkat struktur dalam tensor, sementara "shape" atau "bentuk" memberikan informasi tentang seberapa banyak elemen yang terdapat dalam setiap dimensi.



Selanjutnya membuat **tensor**

In [ ]:
# membuat Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

Kode di atas menciptakan sebuah tensor dengan tiga dimensi, di mana terdapat tiga tingkat struktur data. Tensor ini dapat dianggap sebagai kumpulan matriks, di mana setiap matriks 3x3 ditempatkan di dalam tensor induk.

Dapat dilihat, Tensor ini terdiri dari beberapa matriks. Untuk mengetahui ukurannya, kita dapat memeriksa dimensi dan bentuk (shape) dari Tensor yang telah kita buat sebelumnya

In [ ]:
# Check number of dimensions for TENSOR
TENSOR.ndim

3

Tensor memiliki ukuran sebesar 3, selanjutnya mengecek bentuk `TENSOR`

In [ ]:
# Check shape of TENSOR
TENSOR.shape

torch.Size([1, 3, 3])

Output `torch.Size([1, 3, 3])` menunjukkan bahwa tensor tersebut memiliki tiga dimensi dengan panjang masing-masing dimensi adalah 1, 3, dan 3. Dimensinya dari luar ke dalam, hal tersebut menandakan bahwa tensor ini memiliki satu salinan, dan setiap salinan terdiri dari tiga baris dan tiga kolom.


![example of different tensor dimensions](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-pytorch-different-tensor-dimensions.png)

Setelah melakukan beberapa percobaan pada scalar, vector, matrix dan tensor, kesimpulan yang didapatkan adalah:

| Nama | Penjelasan | Jumlah Dimensi | Tanda yang biasa digunakan dalam latihan ini |
| ----- | ----- | ----- | ----- |
| **scalar** | tensor dengan dimensi nol, yang berarti hanya mengandung satu nilai tunggal | 0 | Lower (`a`) |
| **vector** | tensor satu dimensi yang berisi sekumpulan nilai | 1 | Lower (`y`) |
| **matrix** | tensor dua dimensi yang terdiri dari baris dan kolom | 2 | Upper (`Q`) |
| **tensor** | baris bilangan n-dimensi | dapat berupa bilangan apa saja, tensor 0 dimensi adalah skalar, tensor 1 dimensi adalah vektor | Upper (`X`) |

Untuk memudahkan pemahaman mengenai scalar, vector, matrix dan tensor, dapat dilihat pada gambar di bawah ini.

![scalar vector matrix tensor and what they look like](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-scalar-vector-matrix-tensor.png)

### Random tensors


Random tensors dalam konteks PyTorch merujuk pada pembuatan tensor dengan nilai-nilai yang dihasilkan secara acak. PyTorch menyediakan fungsi dan modul untuk menghasilkan random tensors dengan berbagai distribusi.

Catatan dari materi ini: Kami telah menetapkan bahwa tensor mewakili beberapa bentuk data.

Dan model pembelajaran mesin seperti jaringan syaraf tiruan memanipulasi dan mencari pola di dalam tensor.

Namun, ketika membangun model pembelajaran mesin dengan PyTorch, jarang sekali Anda membuat tensor dengan tangan (seperti yang kita lakukan).

Sebaliknya, model pembelajaran mesin sering kali dimulai dengan tensor angka acak yang besar dan menyesuaikan angka acak ini saat bekerja melalui data untuk merepresentasikannya dengan lebih baik.

Intinya:

`Mulai dengan angka acak -> lihat data -> perbarui angka acak -> lihat data -> perbarui angka acak...`

Sebagai seorang ilmuwan data, Anda dapat menentukan bagaimana model machine learning memulai (inisialisasi), melihat data (representasi), dan memperbarui (optimasi) angka-angka acak.

Kita akan membahas langkah-langkah ini nanti.

Untuk saat ini, mari kita lihat bagaimana cara membuat tensor bilangan acak.


Hal ini dapat dilakukan dengan [`torch.rand()`](https://pytorch.org/docs/stable/generated/torch.rand.html) dan memasukkan parameter `size`.

In [ ]:
# membuat random tensor dengan ukuran (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.1086, 0.5956, 0.0901, 0.5975],
         [0.9820, 0.6489, 0.2166, 0.5995],
         [0.6719, 0.1667, 0.3120, 0.9764]]),
 torch.float32)

Fleksibilitas dari `torch.rand()` adalah, kita dapat menyesuaikan ukurannya menjadi apa pun yang kita inginkan.

Sebagai contoh, kita menginginkan tensor acak dalam bentuk gambar umum `[224, 224, 3]` (`[height, width, color_channels`]).

In [ ]:
 # membuat random tensor dengan ukuran (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

 Output yang dihasilkan menjelaskan bahwa tensor ini memiliki tiga dimensi dengan ukuran masing-masing dimensi adalah 224, 224, dan 3. Dimensi pertama dan kedua merepresentasikan tinggi dan lebar citra, sedangkan dimensi ketiga merepresentasikan jumlah channel warna.

### Zeros and ones

Terkadang kita hanya ingin mengisi tensor dengan nol atau satu.

Hal ini sering terjadi pada masking (seperti menutupi beberapa nilai dalam satu tensor dengan nol agar model tidak mempelajarinya).

Selanjutnya membuat tensor yang hanya berisi angka nol [`torch.zeros()`](https://pytorch.org/docs/stable/generated/torch.zeros.html)


Di sini kita akan menggunakan parameter `size` lagi.

In [ ]:
# Membuat tensor 3x4 dengan isi nol
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

Output menghasilkan tensor dengan ukuran 3x4 yang berisi angka nol (zeros).

Kita juga dapat melakukan hal tersebut dengan hanya mengisi angka 1 (ones) menggunakan [`torch.ones()` ](https://pytorch.org/docs/stable/generated/torch.ones.html)

In [ ]:
# Membuat tensor 3x4 dengan isi satu
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

Tensor yang dihasilkan berisi angka 1 dengan ukuran 3x4

### Membuat rentang dan tensor

Ketika kita menginginkan rentang angka, seperti 1 hingga 10 atau 0 hingga 100.

Jika range yang biasa kita buat di Python menggunakan `range()` kita dapat menggunakan `torch.arange(start, end, step)` untuk melakukannya di tensor.

Di mana:
* `start` = awal rentang (mis. 0)
* `end` = akhir rentang (misalnya 10)
* `step` = berapa banyak langkah di antara setiap nilai (misalnya 1)


In [ ]:
# Use torch.arange(), torch.range() is deprecated
zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future

# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

<ipython-input-18-a404776195c1>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Tensor ini mencakup nilai-nilai integer dari 0 hingga 9, dihasilkan dengan menggunakan fungsi torch.arange() dengan parameter start=0, end=10 (perhatikan bahwa end adalah nilai yang tidak dimasukkan dalam rentang), dan step=1. Hasilnya adalah tensor yang mencakup setiap nilai dalam rentang tersebut.

Sometimes you might want one tensor of a certain type with the same

1.   Item daftar
2.   Item daftar

shape as another tensor.

For example, a tensor of all zeros with the same shape as a previous tensor.

To do so you can use [`torch.zeros_like(input)`](https://pytorch.org/docs/stable/generated/torch.zeros_like.html) or [`torch.ones_like(input)`](https://pytorch.org/docs/1.9.1/generated/torch.ones_like.html) which return a tensor filled with zeros or ones in the same shape as the `input` respectively.

Kita juga dapat melakukan hal yang sama dengan tensor yang hanya berisi angka 0 dengan menggunakan [`torch.zeros_like(input)`](https://pytorch.org/docs/stable/generated/torch.zeros_like.html) atau [`torch.ones_like(input)`](https://pytorch.org/docs/1.9.1/generated/torch.ones_like.html).

In [ ]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Seperti yang dapat dilihat pada output, tensor berisi angka nol (zeros) dengan range 0 sampai 10.

### Tipe Data Tensor

In [ ]:
# Tipe data default untuk tensor adalah float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

Kode di atas menciptakan tensor dengan tipe data float32 secara eksplisit dan menunjukkan informasi tentang bentuk (shape), tipe data, dan perangkat tempat tensor disimpan, tensor ini adalah 1 dimensi dengan panjang 3, menyimpan nilai-nilai dengan presisi floating-point 32-bit. Tensor ini disimpan di CPU

Selain masalah bentuk (bentuk tensor yang tidak sama), dua masalah paling umum lainnya yang akan Anda temui di PyTorch adalah masalah tipe data dan perangkat.

Sebagai contoh, salah satu tensor adalah torch.float32 dan yang lainnya adalah torch.float16 (PyTorch sering kali menyukai tensor dengan format yang sama).

Atau salah satu tensor Anda ada di CPU dan yang lainnya ada di GPU (PyTorch menyukai kalkulasi antar tensor berada di perangkat yang sama).

Kita akan membahas lebih lanjut tentang perangkat ini nanti.

Untuk saat ini, mari kita buat sebuah tensor dengan dtype=torch.float16.

In [ ]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

kode ini menghasilkan tensor dengan nilai float dan tipe data float16, yang berguna dalam situasi di mana hemat memori diperlukan dan kehilangan presisi dapat diterima.

## Mendapatkan Informasi dari Tensor

Setelah membuat tensor, kita mungkin ingin mendapatkan beberapa informasi dari tensor.

Kita sudah pernah melihat ini sebelumnya, tetapi tiga atribut yang paling umum yang ingin Anda ketahui tentang tensor adalah:
* `shape` - bagaimana bentuk tensor tersebut? (beberapa operasi memerlukan aturan bentuk tertentu)
* `dtype` - dalam tipe data apa elemen-elemen di dalam tensor disimpan?
* `device` - pada perangkat apa tensor disimpan? (biasanya GPU atau CPU)

In [ ]:
# Buat Tensor
some_tensor = torch.rand(3, 4)

# Mendapatkan Informasi Detail dari Tensor
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # mengikuti CPU default

tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Manipulasi Tensor (operasi tensor)

In deep learning, data (images, text, video, audio, protein structures, etc) gets represented as tensors.

A model learns by investigating those tensors and performing a series of operations (could be 1,000,000s+) on tensors to create a representation of the patterns in the input data.

These operations are often a wonderful dance between:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

And that's it. Sure there are a few more here and there but these are the basic building blocks of neural networks.

Stacking these building blocks in the right way, you can create the most sophisticated of neural networks (just like lego!).

### Operasi Dasar
Let's start with a few of the fundamental operations, addition (`+`), subtraction (`-`), mutliplication (`*`).

They work just as you think they would.

In [ ]:
# Membuat tensor dengan nilai [1, 2, 3]
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

Tensor yang memiliki nilai [11, 12, 13], namun nilai ini tidak disimpan secara permanen ke dalam tensor tensor.

In [ ]:
# Mengalikan setiap elemen tensor dengan 10
tensor * 10

tensor([10, 20, 30])

Tensor yang memiliki nilai [10, 20, 30], namun nilai ini juga tidak disimpan secara permanen.

In [ ]:
# Tidak ada perubahan pada tensor asli tanpa reassign
tensor

tensor([1, 2, 3])

Tensor tetap memiliki nilai [1, 2, 3], karena operasi sebelumnya tidak diassign kembali ke tensor.

In [ ]:
# Mengurangkan nilai 10 dari setiap elemen tensor dan men-assign kembali
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

Tensor sekarang memiliki nilai [-9, -8, -7], karena nilai 10 dikurangkan dari setiap elemen dan diassign kembali ke tensor.

In [ ]:
# Menambah nilai 10 ke setiap elemen tensor dan men-assign kembali
tensor = tensor + 10
tensor

tensor([1, 2, 3])

Tensor kembali memiliki nilai [1, 2, 3], karena nilai 10 ditambahkan ke setiap elemen dan diassign kembali ke tensor.

In [ ]:
# Menggunakan fungsi multiply dari torch untuk mengalikan setiap elemen dengan 10
torch.multiply(tensor, 10)

tensor([10, 20, 30])

Tensor dengan nilai [10, 20, 30], namun nilai ini tidak disimpan secara permanen ke dalam tensor.

In [ ]:
# Tensor asli tidak berubah, masih [1, 2, 3]
tensor


tensor([1, 2, 3])

Tensor tetap memiliki nilai [1, 2, 3], karena operasi sebelumnya tidak mengubah tensor asli.

In [ ]:
# Perkalian elemen-wise (setiap elemen dikali elemen yang setara, indeks 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)
tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


Penjelasan: Operasi perkalian elemen-wise menghasilkan tensor baru yang nilai-nilainya merupakan hasil perkalian setiap elemen pada posisi yang sama.

### Perkalian Matrix

One of the most common operations in machine learning and deep learning algorithms (like neural networks) is [matrix multiplication](https://www.mathsisfun.com/algebra/matrix-multiplying.html).

PyTorch implements matrix multiplication functionality in the [`torch.matmul()`](https://pytorch.org/docs/stable/generated/torch.matmul.html) method.

The main two rules for matrix multiplication to remember are:

1. The **inner dimensions** must match:
  * `(3, 2) @ (3, 2)` won't work
  * `(2, 3) @ (3, 2)` will work
  * `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
 * `(2, 3) @ (3, 2)` -> `(2, 2)`
 * `(3, 2) @ (2, 3)` -> `(3, 3)`

> **Note:** "`@`" in Python is the symbol for matrix multiplication.

> **Resource:** You can see all of the rules for matrix multiplication using `torch.matmul()` [in the PyTorch documentation](https://pytorch.org/docs/stable/generated/torch.matmul.html).

Let's create a tensor and perform element-wise multiplication and matrix multiplication on it.



In [ ]:
import torch

# Membuat tensor dengan nilai [1, 2, 3]
tensor = torch.tensor([1, 2, 3])
tensor.shape


torch.Size([3])

torch.Size([3]), menunjukkan bahwa tensor ini adalah tensor 1 dimensi dengan panjang 3.

In [ ]:
# Perkalian elemen-wise pada tensor
tensor * tensor


tensor([1, 4, 9])

In [ ]:
# Perkalian matriks menggunakan torch.matmul
torch.matmul(tensor, tensor)


tensor(14)

14, hasil dari perkalian matriks antara tensor dan dirinya sendiri.

In [ ]:
# Can also use the "@" symbol for matrix multiplication, though not recommended
tensor @ tensor

tensor(14)

Operasi tensor * tensor menghasilkan perkalian elemen-wise pada tensor, menghasilkan tensor baru dengan nilai [1, 4, 9].
torch.matmul(tensor, tensor) menghasilkan perkalian matriks antara tensor dan dirinya sendiri, menghasilkan skalar 14.
Penggunaan simbol "@" memiliki hasil yang sama dengan torch.matmul, tetapi penggunaan torch.matmul lebih disarankan untuk kejelasan kode.

Kita bisa menggunakan perkalian matrix menggunakan `torch.matmul()`.

In [ ]:
%%time
# Perkalian matriks secara manual
# (hindari melakukan operasi dengan for loop sebisa mungkin, karena mereka mahal secara komputasi)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value


CPU times: user 442 µs, sys: 0 ns, total: 442 µs
Wall time: 645 µs


tensor(14)

In [ ]:
%%time
torch.matmul(tensor, tensor)


CPU times: user 78 µs, sys: 0 ns, total: 78 µs
Wall time: 82.5 µs


tensor(14)

## Error yang biasa terjadi di Deep Learning (shape error)

Because much of deep learning is multiplying and performing operations on matrices and matrices have a strict rule about what shapes and sizes can be combined, one of the most common errors you'll run into in deep learning is shape mismatches.

In [ ]:
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

tensor([[ 23.,  32.],
        [ 53.,  74.],
        [ 83., 116.]])

Bentuk dari tensor_A dan tensor_B tidak dapat dikalikan (3x2 dan 3x2), maka dari itu kita mengubah bentuk dari salah satu tensor, di sini saya mengubah bentuk dari tensor_B menjadi 2x2   

We can make matrix multiplication work between `tensor_A` and `tensor_B` by making their inner dimensions match.

One of the ways to do this is with a **transpose** (switch the dimensions of a given tensor).

You can perform transposes in PyTorch using either:
* `torch.transpose(input, dim0, dim1)` - where `input` is the desired tensor to transpose and `dim0` and `dim1` are the dimensions to be swapped.
* `tensor.T` - where `tensor` is the desired tensor to transpose.

Let's try the latter.

In [ ]:
# Menampilkan tensor_A dan tensor_B
print(tensor_A)
print(tensor_B)


tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.]])


Menampilkan nilai tensor_A dan tensor_B.

In [ ]:
# Menampilkan tensor_A dan transpose dari tensor_B
print(tensor_A)
print(tensor_B.T)


tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.],
        [10., 11.]])


Menampilkan nilai tensor_A dan transpose dari tensor_B.

In [ ]:
# Operasi perkalian matriks bekerja ketika tensor_B di-transpose
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (sama seperti sebelumnya), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- dimensi dalam cocok\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")


Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([2, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 2])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 2]) <- inner dimensions match

Output:

tensor([[ 27.,  30.],
        [ 61.,  68.],
        [ 95., 106.]])

Output shape: torch.Size([3, 2])


Menampilkan informasi tentang bentuk asli dan bentuk baru dari tensor_A dan tensor_B.T. Kemudian, melakukan perkalian matriks antara tensor_A dan transpose dari tensor_B, dan menampilkan hasilnya beserta bentuknya.

Kita juga bisa menggunakan [`torch.mm()`](https://pytorch.org/docs/stable/generated/torch.mm.html) versi lebih pendek dari `torch.matmul()`.

In [ ]:
# torch.mm adalah singkatan dari matmul
torch.mm(tensor_A, tensor_B.T)


tensor([[ 27.,  30.],
        [ 61.,  68.],
        [ 95., 106.]])

Hasil dari operasi perkalian matriks menggunakan fungsi torch.mm antara tensor_A dan transpose dari tensor_B.

Without the transpose, the rules of matrix mulitplication aren't fulfilled and we get an error like above.

How about a visual?

![visual demo of matrix multiplication](https://github.com/mrdbourke/pytorch-deep-learning/raw/main/images/00-matrix-multiply-crop.gif)

You can create your own matrix multiplication visuals like this at http://matrixmultiplication.xyz/.

> **Note:** A matrix multiplication like this is also referred to as the [**dot product**](https://www.mathsisfun.com/algebra/vectors-dot-product.html) of two matrices.



Neural networks are full of matrix multiplications and dot products.

The [`torch.nn.Linear()`](https://pytorch.org/docs/1.9.1/generated/torch.nn.Linear.html) module (we'll see this in action later on), also known as a feed-forward layer or fully connected layer, implements a matrix multiplication between an input `x` and a weights matrix `A`.

$$
y = x\cdot{A^T} + b
$$

Where:
* `x` is the input to the layer (deep learning is a stack of layers like `torch.nn.Linear()` and others on top of each other).
* `A` is the weights matrix created by the layer, this starts out as random numbers that get adjusted as a neural network learns to better represent patterns in the data (notice the "`T`", that's because the weights matrix gets transposed).
  * **Note:** You might also often see `W` or another letter like `X` used to showcase the weights matrix.
* `b` is the bias term used to slightly offset the weights and inputs.
* `y` is the output (a manipulation of the input in the hopes to discover patterns in it).

This is a linear function (you may have seen something like $y = mx+b$ in high school or elsewhere), and can be used to draw a straight line!

Let's play around with a linear layer.

Try changing the values of `in_features` and `out_features` below and see what happens.

Do you notice anything to do with the shapes?

In [ ]:
# Karena layer linear dimulai dengan matriks berbobot acak, mari membuatnya dapat direproduksi (lebih banyak tentang ini nanti)
torch.manual_seed(42)
# Ini menggunakan perkalian matriks
linear = torch.nn.Linear(in_features=2, # in_features = cocokkan dengan dimensi dalam input
                         out_features=6) # out_features = deskripsikan dimensi luar
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")


Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


Menampilkan bentuk input, hasil output, dan bentuk output dari layer linear.

> **Question:** What happens if you change `in_features` from 2 to 3 above? Does it error? How could you change the shape of the input (`x`) to accomodate to the error? Hint: what did we have to do to `tensor_B` above?

If you've never done it before, matrix multiplication can be a confusing topic at first.

But after you've played around with it a few times and even cracked open a few neural networks, you'll notice it's everywhere.

Remember, matrix multiplication is all you need.

![matrix multiplication is all you need](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00_matrix_multiplication_is_all_you_need.jpeg)

*When you start digging into neural network layers and building your own, you'll find matrix multiplications everywhere. **Source:** https://marksaroufim.substack.com/p/working-class-deep-learner*

### Finding the min, max, mean, sum, etc (aggregation)

Now we've seen a few ways to manipulate tensors, let's run through a few ways to aggregate them (go from more values to less values).

First we'll create a tensor and then find the max, min, mean and sum of it.





In [ ]:
# Membuat tensor
x = torch.arange(0, 100, 10)
x


tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

Tensor yang dibuat dengan menggunakan fungsi torch.arange dengan parameter start=0, end=100, dan step=10.

torch.arange(0, 100, 10) membuat tensor dengan rentang nilai dari 0 hingga kurang dari 100, dengan langkah 10.
Hasilnya adalah tensor dengan nilai [0, 10, 20, 30, 40, 50, 60, 70, 80, 90].

Mencoba agregasi

In [ ]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # ini akan error
print(f"Mean: {x.type(torch.float32).mean()}") # tidak akan berfungsi tanpa tipe data float
print(f"Sum: {x.sum()}")


Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


Menampilkan nilai minimum, maksimum, rata-rata, dan jumlah dari tensor x

x.min() mengembalikan nilai minimum dari tensor x.
x.max() mengembalikan nilai maksimum dari tensor x.
x.mean() akan menghasilkan error karena operasi mean memerlukan tipe data float. Oleh karena itu, x.type(torch.float32).mean() digunakan untuk mengubah tipe data tensor menjadi float sebelum menghitung rata-rata.
x.sum() mengembalikan jumlah dari semua elemen dalam tensor x.

> **Note:** You may find some methods such as `torch.mean()` require tensors to be in `torch.float32` (the most common) or another specific datatype, otherwise the operation will fail.

You can also do the same as above with `torch` methods.

In [ ]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

Tuple yang berisi nilai maksimum, nilai minimum, rata-rata (dengan tipe data float32), dan jumlah dari tensor x.

torch.max(x) mengembalikan nilai maksimum dari tensor x.
torch.min(x) mengembalikan nilai minimum dari tensor x.
torch.mean(x.type(torch.float32)) mengembalikan rata-rata dari tensor x setelah diubah tipe datanya menjadi float32.
torch.sum(x) mengembalikan jumlah dari semua elemen dalam tensor x.

### Positional min/max

You can also find the index of a tensor where the max or minimum occurs with [`torch.argmax()`](https://pytorch.org/docs/stable/generated/torch.argmax.html) and [`torch.argmin()`](https://pytorch.org/docs/stable/generated/torch.argmin.html) respectively.

This is helpful incase you just want the position where the highest (or lowest) value is and not the actual value itself (we'll see this in a later section when using the [softmax activation function](https://pytorch.org/docs/stable/generated/torch.nn.Softmax.html)).

In [ ]:
# Membuat tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Mengembalikan indeks dari nilai maksimum dan minimum
print(f"Indeks di mana nilai maksimum terjadi: {tensor.argmax()}")
print(f"Indeks di mana nilai minimum terjadi: {tensor.argmin()}")


Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


Menampilkan tensor yang dibuat dan indeks dari nilai maksimum dan minimum dalam tensor.

torch.arange(10, 100, 10) membuat tensor dengan rentang nilai dari 10 hingga kurang dari 100, dengan langkah 10. Hasilnya adalah tensor dengan nilai [10, 20, 30, 40, 50, 60, 70, 80, 90].
tensor.argmax() mengembalikan indeks di mana nilai maksimum dalam tensor terjadi.
tensor.argmin() mengembalikan indeks di mana nilai minimum dalam tensor terjadi.

### Change tensor datatype

As mentioned, a common issue with deep learning operations is having your tensors in different datatypes.

If one tensor is in `torch.float64` and another is in `torch.float32`, you might run into some errors.

But there's a fix.

You can change the datatypes of tensors using [`torch.Tensor.type(dtype=None)`](https://pytorch.org/docs/stable/generated/torch.Tensor.type.html) where the `dtype` parameter is the datatype you'd like to use.

First we'll create a tensor and check it's datatype (the default is `torch.float32`).

In [ ]:
# Membuat tensor dan memeriksa tipe datanya
tensor = torch.arange(10., 100., 10.)
tensor.dtype


torch.float32

Menampilkan tipe data dari tensor yang dibuat

Now we'll create another tensor the same as before but change its datatype to `torch.float16`.



In [ ]:
# Membuat tensor dengan tipe data float16
tensor_float16 = tensor.type(torch.float16)
tensor_float16


tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

Menampilkan tensor yang dibuat dengan tipe data float16

And we can do something similar to make a `torch.int8` tensor.

In [ ]:
# Membuat tensor dengan tipe data int8
tensor_int8 = tensor.type(torch.int8)
tensor_int8


tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

Menampilkan tensor yang dibuat dengan tipe data int8.

tensor.type(torch.int8) mengubah tipe data tensor menjadi int8.
tensor_int8 adalah tensor hasil konversi dengan tipe data int8. Perlu dicatat bahwa penggunaan int8 dapat menyebabkan overflow atau underflow tergantung pada nilai-nilai dalam tensor.

# > **Note:** Different datatypes can be confusing to begin with. But think of it like this, the lower the number (e.g. 32, 16, 8), the less precise a computer stores the value. And with a lower amount of storage, this generally results in faster computation and a smaller overall model. Mobile-based neural networks often operate with 8-bit integers, smaller and faster to run but less accurate than their float32 counterparts. For more on this, I'd read up about [precision in computing](https://en.wikipedia.org/wiki/Precision_(computer_science)).

> **Exercise:** So far we've covered a fair few tensor methods but there's a bunch more in the [`torch.Tensor` documentation](https://pytorch.org/docs/stable/tensors.html), I'd recommend spending 10-minutes scrolling through and looking into any that catch your eye. Click on them and then write them out in code yourself to see what happens.

### Reshaping, stacking, squeezing and unsqueezing

Often times you'll want to reshape or change the dimensions of your tensors without actually changing the values inside them.

To do so, some popular methods are:

| Method | One-line description |
| ----- | ----- |
| [`torch.reshape(input, shape)`](https://pytorch.org/docs/stable/generated/torch.reshape.html#torch.reshape) | Reshapes `input` to `shape` (if compatible), can also use `torch.Tensor.reshape()`. |
| [`Tensor.view(shape)`](https://pytorch.org/docs/stable/generated/torch.Tensor.view.html) | Returns a view of the original tensor in a different `shape` but shares the same data as the original tensor. |
| [`torch.stack(tensors, dim=0)`](https://pytorch.org/docs/1.9.1/generated/torch.stack.html) | Concatenates a sequence of `tensors` along a new dimension (`dim`), all `tensors` must be same size. |
| [`torch.squeeze(input)`](https://pytorch.org/docs/stable/generated/torch.squeeze.html) | Squeezes `input` to remove all the dimenions with value `1`. |
| [`torch.unsqueeze(input, dim)`](https://pytorch.org/docs/1.9.1/generated/torch.unsqueeze.html) | Returns `input` with a dimension value of `1` added at `dim`. |
| [`torch.permute(input, dims)`](https://pytorch.org/docs/stable/generated/torch.permute.html) | Returns a *view* of the original `input` with its dimensions permuted (rearranged) to `dims`. |

Why do any of these?

Because deep learning models (neural networks) are all about manipulating tensors in some way. And because of the rules of matrix multiplication, if you've got shape mismatches, you'll run into errors. These methods help you make sure the right elements of your tensors are mixing with the right elements of other tensors.

Let's try them out.

First, we'll create a tensor.

In [ ]:
# Membuat tensor
import torch
x = torch.arange(1., 8.)
x, x.shape


(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

Menampilkan tensor yang dibuat dan bentuknya.


torch.arange(1., 8.) membuat tensor dengan rentang nilai dari 1 hingga kurang dari 8, dengan langkah default 1, dan menggunakan tipe data float.
x adalah tensor yang dibuat.
x.shape mengembalikan bentuk dari tensor x. Dalam hal ini, bentuknya adalah (7,), menunjukkan bahwa ini adalah tensor satu dimensi dengan panjang 7.

Now let's add an extra dimension with `torch.reshape()`.

In [ ]:
# Menambah dimensi tambahan
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape


(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

Menampilkan tensor yang telah ditambahkan dimensi tambahan dan bentuknya.

x.reshape(1, 7) mengubah bentuk tensor x menjadi (1, 7), menambahkan dimensi tambahan di sepanjang dimensi pertama.
x_reshaped adalah tensor yang telah mengalami reshaping.
x_reshaped.shape mengembalikan bentuk dari tensor x_reshaped, yang sekarang adalah (1, 7).

We can also change the view with `torch.view()`.

In [ ]:
# Mengubah tampilan (memiliki data yang sama dengan aslinya tetapi mengubah tampilan)
# Lihat lebih lanjut: https://stackoverflow.com/a/54507446/7900723
z = x.view(1, 7)
z, z.shape


(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

Menampilkan tensor yang telah mengalami perubahan tampilan dan bentuknya.

Penjelasan:

x.view(1, 7) mengubah tampilan tensor x menjadi (1, 7), tetapi mempertahankan data yang sama seperti aslinya.
z adalah tensor yang telah mengalami perubahan tampilan.
z.shape mengembalikan bentuk dari tensor z, yang sekarang adalah (1, 7). Perhatikan bahwa ini mempertahankan jumlah elemen yang sama dengan tensor asli, hanya mengubah cara tensor diorganisir dalam memori.

Remember though, changing the view of a tensor with `torch.view()` really only creates a new view of the *same* tensor.

So changing the view changes the original tensor too.

In [ ]:
# Mengubah z mengubah x
z[:, 0] = 5
z, x


(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

Menampilkan tensor z setelah diubah, dan menunjukkan bahwa perubahan di tensor z juga mempengaruhi tensor x.

Penjelasan:

Memodifikasi elemen pertama dari kolom pertama tensor z dengan z[:, 0] = 5 mengakibatkan perubahan nilai tersebut.
Karena z dan x berbagi data yang sama setelah operasi view, perubahan yang dilakukan di tensor z juga tercermin di tensor x. Hal ini menunjukkan bahwa keduanya menggunakan memori yang sama, dan perubahan di salah satu tensor akan mempengaruhi tensor lainnya.

If we wanted to stack our new tensor on top of itself five times, we could do so with `torch.stack()`.

In [ ]:
# Menumpuk tensor satu di atas yang lain
x_stacked = torch.stack([x, x, x, x], dim=0) # coba ubah dim menjadi dim=1 dan lihat apa yang terjadi
x_stacked


tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

Menampilkan tensor yang telah ditumpuk secara vertikal (berdasarkan dimensi 0) dari tensor x.

Penjelasan:

torch.stack([x, x, x, x], dim=0) melakukan penumpukan vertikal dari tensor-tensor dalam list.
Hasilnya adalah tensor dengan dimensi baru (4, 7), di mana 4 adalah jumlah tensor yang ditumpuk dan 7 adalah panjang tensor x.
Jika dim diubah menjadi dim=1, maka penumpukan akan dilakukan secara horizontal, dan dimensi baru menjadi (1, 28).

How about removing all single dimensions from a tensor?

To do so you can use `torch.squeeze()` (I remember this as *squeezing* the tensor to only have dimensions over 1).

In [ ]:
# Menampilkan tensor dan bentuk sebelumnya
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Menghapus dimensi tambahan dari x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")


Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


Menampilkan tensor sebelum dan setelah dimensi tambahan dihapus, serta bentuk masing-masing.

Penjelasan:

x_reshaped adalah tensor dengan dimensi (1, 7) setelah dimensi tambahan ditambahkan sebelumnya.
x_reshaped.squeeze() menghapus dimensi tambahan, sehingga tensor menjadi (7,).
Hasilnya adalah tensor baru x_squeezed dan bentuk baru yang mencerminkan perubahan tersebut.






And to do the reverse of `torch.squeeze()` you can use `torch.unsqueeze()` to add a dimension value of 1 at a specific index.

In [ ]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Menambah dimensi tambahan dengan unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")


Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


Menampilkan tensor sebelum dan setelah dimensi tambahan ditambahkan kembali menggunakan unsqueeze, serta bentuk masing-masing.

Penjelasan:

x_squeezed adalah tensor dengan dimensi (7,) setelah dimensi tambahan dihapus sebelumnya.
x_squeezed.unsqueeze(dim=0) menambahkan dimensi tambahan di posisi pertama, sehingga tensor menjadi (1, 7).
Hasilnya adalah tensor baru x_unsqueezed dan bentuk baru yang mencerminkan perubahan tersebut.






In [ ]:
# Membuat tensor dengan bentuk tertentu
x_original = torch.rand(size=(224, 224, 3))

# Mengubah urutan sumbu dengan permute pada tensor asli
x_permuted = x_original.permute(2, 0, 1) # menggeser sumbu 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")


Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


Menampilkan bentuk tensor sebelum dan setelah diubah menggunakan permute.

Penjelasan:

torch.rand(size=(224, 224, 3)) membuat tensor dengan bentuk (224, 224, 3) dan nilai acak.
x_original.permute(2, 0, 1) mengubah urutan sumbu tensor, sehingga sumbu 0 pindah ke posisi 1, sumbu 1 pindah ke posisi 2, dan sumbu 2 pindah ke posisi 0.
Hasilnya adalah tensor baru x_permuted dengan bentuk yang diubah.






> **Note**: Because permuting returns a *view* (shares the same data as the original), the values in the permuted tensor will be the same as the original tensor and if you change the values in the view, it will change the values of the original.

## Indexing (selecting data from tensors)

Sometimes you'll want to select specific data from tensors (for example, only the first column or second row).

To do so, you can use indexing.

If you've ever done indexing on Python lists or NumPy arrays, indexing in PyTorch with tensors is very similar.

In [ ]:
# Membuat tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape


(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

Menampilkan tensor yang dibuat dan bentuknya.

Penjelasan:

torch.arange(1, 10) membuat tensor dengan rentang nilai dari 1 hingga kurang dari 10.
.reshape(1, 3, 3) mengubah bentuk tensor menjadi (1, 3, 3), menambahkan dimensi tambahan.
x adalah tensor yang dibuat.
x.shape mengembalikan bentuk dari tensor x, yang sekarang adalah (1, 3, 3).






Indexing values goes outer dimension -> inner dimension (check out the square brackets).

In [ ]:
# Mari melakukan indexing berdasarkan kurung siku
print(f"First square bracket:\n{x[0]}")
print(f"Second square bracket: {x[0][0]}")
print(f"Third square bracket: {x[0][0][0]}")


First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


Menampilkan hasil indexing dari tensor menggunakan kurung siku.

Penjelasan:

x[0] mengambil elemen pada indeks 0 dari dimensi pertama tensor x, menghasilkan tensor dengan bentuk (3, 3).
x[0][0] mengambil elemen pada indeks 0 dari dimensi kedua tensor sebelumnya, menghasilkan tensor dengan bentuk (3,).
x[0][0][0] mengambil elemen pada indeks 0 dari dimensi ketiga tensor sebelumnya, menghasilkan nilai tunggal.

You can also use `:` to specify "all values in this dimension" and then use a comma (`,`) to add another dimension.

In [ ]:
# Mengambil semua nilai dimensi ke-0 dan indeks ke-0 dari dimensi ke-1
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
# Mengambil semua nilai dimensi ke-0 dan ke-1 tetapi hanya indeks ke-1 dari dimensi ke-2
x[:, :, 1]


tensor([[2, 5, 8]])

In [ ]:
# Mengambil semua nilai dimensi ke-0 tetapi hanya nilai indeks ke-1 dari dimensi ke-1 dan ke-2
x[:, 1, 1]


tensor([5])

In [ ]:
# Mengambil indeks ke-0 dari dimensi ke-0 dan ke-1 serta semua nilai dari dimensi ke-2
x[0, 0, :] # sama dengan x[0][0]

tensor([1, 2, 3])

Menampilkan hasil indexing dari tensor x dengan menggunakan indeks tertentu.

Penjelasan:

x[:, 0] mengambil semua nilai dari dimensi ke-0 dan indeks ke-0 dari dimensi ke-1, menghasilkan tensor dengan bentuk (3,).
x[:, :, 1] mengambil semua nilai dari dimensi ke-0 dan ke-1, tetapi hanya indeks ke-1 dari dimensi ke-2, menghasilkan tensor dengan bentuk (1, 3).
x[:, 1, 1] mengambil semua nilai dari dimensi ke-0, tetapi hanya nilai indeks ke-1 dari dimensi ke-1 dan ke-2, menghasilkan nilai tunggal.
x[0, 0, :] atau x[0][0] mengambil nilai pada indeks ke-0 dari dimensi ke-0 dan ke-1, serta semua nilai dari dimensi ke-2, menghasilkan tensor dengan bentuk (3,).






Indexing can be quite confusing to begin with, especially with larger tensors (I still have to try indexing multiple times to get it right). But with a bit of practice and following the data explorer's motto (***visualize, visualize, visualize***), you'll start to get the hang of it.

## PyTorch tensors & NumPy

Since NumPy is a popular Python numerical computing library, PyTorch has functionality to interact with it nicely.  

The two main methods you'll want to use for NumPy to PyTorch (and back again) are:
* [`torch.from_numpy(ndarray)`](https://pytorch.org/docs/stable/generated/torch.from_numpy.html) - NumPy array -> PyTorch tensor.
* [`torch.Tensor.numpy()`](https://pytorch.org/docs/stable/generated/torch.Tensor.numpy.html) - PyTorch tensor -> NumPy array.

Let's try them out.

In [ ]:
# NumPy array ke tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor


(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

Menampilkan array NumPy dan tensor yang dihasilkan dari konversi.

Penjelasan:

np.arange(1.0, 8.0) membuat array NumPy dengan rentang nilai dari 1.0 hingga kurang dari 8.0.
torch.from_numpy(array) mengonversi array NumPy menjadi tensor PyTorch.
array adalah array NumPy yang dibuat.
tensor adalah tensor hasil konversi dari array NumPy.






> **Note:** By default, NumPy arrays are created with the datatype `float64` and if you convert it to a PyTorch tensor, it'll keep the same datatype (as above).
>
> However, many PyTorch calculations default to using `float32`.
>
> So if you want to convert your NumPy array (float64) -> PyTorch tensor (float64) -> PyTorch tensor (float32), you can use `tensor = torch.from_numpy(array).type(torch.float32)`.

Because we reassigned `tensor` above, if you change the tensor, the array stays the same.

In [ ]:
# Mengubah array, tetap mempertahankan tensor
array = array + 1
array, tensor


(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

Menampilkan array NumPy setelah diubah dan tensor yang tetap tidak berubah.

Penjelasan:

Setelah array NumPy diubah dengan operasi array = array + 1, tensor yang telah dibuat dari array sebelumnya tetap tidak berubah.
Ini menunjukkan bahwa tensor dan array yang berasal dari torch.from_numpy membagi memori yang sama dan perubahan di satu akan tercermin di yang lain.






And if you want to go from PyTorch tensor to NumPy array, you can call `tensor.numpy()`.

In [ ]:
# Tensor ke array NumPy
tensor = torch.ones(7) # membuat tensor dengan nilai satu dengan tipe data float32
numpy_tensor = tensor.numpy() # akan memiliki tipe data float32 kecuali diubah
tensor, numpy_tensor


(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

Menampilkan tensor dan array NumPy yang dihasilkan dari konversi.

Penjelasan:

torch.ones(7) membuat tensor PyTorch dengan tujuh elemen yang memiliki nilai satu.
tensor.numpy() mengonversi tensor PyTorch menjadi array NumPy.
tensor adalah tensor yang dibuat.
numpy_tensor adalah array NumPy yang dihasilkan dari konversi tensor. Perlu dicatat bahwa perubahan di tensor juga akan tercermin di array NumPy karena keduanya berbagi memori yang sama.






And the same rule applies as above, if you change the original `tensor`, the new `numpy_tensor` stays the same.

In [ ]:
# Mengubah tensor, tetap mempertahankan array
tensor = tensor + 1
tensor, numpy_tensor


(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

Menampilkan tensor setelah diubah dan array NumPy yang tetap tidak berubah.

Penjelasan:

Setelah tensor diubah dengan operasi tensor = tensor + 1, array NumPy yang berasal dari tensor sebelumnya tetap tidak berubah.
Ini menunjukkan bahwa tensor dan array yang berasal dari konversi numpy() tidak membagi memori yang sama, dan perubahan di satu tidak memengaruhi yang lain.







## Reproducibility (trying to take the random out of random)

As you learn more about neural networks and machine learning, you'll start to discover how much randomness plays a part.

Well, pseudorandomness that is. Because after all, as they're designed, a computer is fundamentally deterministic (each step is predictable) so the randomness they create are simulated randomness (though there is debate on this too, but since I'm not a computer scientist, I'll let you find out more yourself).

How does this relate to neural networks and deep learning then?

We've discussed neural networks start with random numbers to describe patterns in data (these numbers are poor descriptions) and try to improve those random numbers using tensor operations (and a few other things we haven't discussed yet) to better describe patterns in data.

In short:

``start with random numbers -> tensor operations -> try to make better (again and again and again)``

Although randomness is nice and powerful, sometimes you'd like there to be a little less randomness.

Why?

So you can perform repeatable experiments.

For example, you create an algorithm capable of achieving X performance.

And then your friend tries it out to verify you're not crazy.

How could they do such a thing?

That's where **reproducibility** comes in.

In other words, can you get the same (or very similar) results on your computer running the same code as I get on mine?

Let's see a brief example of reproducibility in PyTorch.

We'll start by creating two random tensors, since they're random, you'd expect them to be different right?

In [ ]:
import torch

# Membuat dua tensor acak
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Apakah Tensor A sama dengan Tensor B? (di mana saja)")
random_tensor_A == random_tensor_B


Tensor A:
tensor([[0.8016, 0.3649, 0.6286, 0.9663],
        [0.7687, 0.4566, 0.5745, 0.9200],
        [0.3230, 0.8613, 0.0919, 0.3102]])

Tensor B:
tensor([[0.9536, 0.6002, 0.0351, 0.6826],
        [0.3743, 0.5220, 0.1336, 0.9666],
        [0.9754, 0.8474, 0.8988, 0.1105]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

Menampilkan kedua tensor acak dan hasil perbandingan element-wise apakah Tensor A sama dengan Tensor B.

Penjelasan:

torch.rand(3, 4) membuat tensor acak dengan bentuk (3, 4).
random_tensor_A == random_tensor_B melakukan perbandingan element-wise antara dua tensor. Hasilnya adalah tensor boolean yang menunjukkan apakah elemen pada posisi yang sesuai dalam kedua tensor sama atau tidak.






Just as you might've expected, the tensors come out with different values.

But what if you wanted to created two random tensors with the *same* values.

As in, the tensors would still contain random values but they would be of the same flavour.

That's where [`torch.manual_seed(seed)`](https://pytorch.org/docs/stable/generated/torch.manual_seed.html) comes in, where `seed` is an integer (like `42` but it could be anything) that flavours the randomness.

Let's try it out by creating some more *flavoured* random tensors.

In [ ]:
import torch
import random

# # Set the random seed
RANDOM_SEED=42 # coba ubah ini menjadi nilai yang berbeda dan lihat apa yang terjadi pada angka di bawah
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# Harus mereset seed setiap kali rand() baru dipanggil
# Tanpa ini, tensor_D akan berbeda dengan tensor_C
torch.random.manual_seed(seed=RANDOM_SEED) # coba komentari baris ini dan lihat apa yang terjadi
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Apakah Tensor C sama dengan Tensor D? (di mana saja)")
random_tensor_C == random_tensor_D


Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

Menampilkan kedua tensor acak yang dihasilkan dengan seed yang ditetapkan, dan hasil perbandingan element-wise apakah Tensor C sama dengan Tensor D.

Penjelasan:

torch.manual_seed(seed=RANDOM_SEED) menetapkan seed untuk generator angka acak PyTorch.
torch.random.manual_seed(seed=RANDOM_SEED) menetapkan seed untuk generator angka acak PyTorch versi baru, yang digunakan oleh fungsi torch.rand().
Mengatur seed memastikan bahwa angka acak yang dihasilkan pada dua tensor tersebut akan sama jika seed-nya sama. Jika seed tidak diatur, nilai tensor_C dan tensor_D mungkin berbeda.






Nice!

It looks like setting the seed worked.

> **Resource:** What we've just covered only scratches the surface of reproducibility in PyTorch. For more, on reproducbility in general and random seeds, I'd checkout:
> * [The PyTorch reproducibility documentation](https://pytorch.org/docs/stable/notes/randomness.html) (a good exericse would be to read through this for 10-minutes and even if you don't understand it now, being aware of it is important).
> * [The Wikipedia random seed page](https://en.wikipedia.org/wiki/Random_seed) (this'll give a good overview of random seeds and pseudorandomness in general).

## Running tensors on GPUs (and making faster computations)

Deep learning algorithms require a lot of numerical operations.

And by default these operations are often done on a CPU (computer processing unit).

However, there's another common piece of hardware called a GPU (graphics processing unit), which is often much faster at performing the specific types of operations neural networks need (matrix multiplications) than CPUs.

Your computer might have one.

If so, you should look to use it whenever you can to train neural networks because chances are it'll speed up the training time dramatically.

There are a few ways to first get access to a GPU and secondly get PyTorch to use the GPU.

> **Note:** When I reference "GPU" throughout this course, I'm referencing a [Nvidia GPU with CUDA](https://developer.nvidia.com/cuda-gpus) enabled (CUDA is a computing platform and API that helps allow GPUs be used for general purpose computing & not just graphics) unless otherwise specified.




### 1. Getting a GPU

You may already know what's going on when I say GPU. But if not, there are a few ways to get access to one.

| **Method** | **Difficulty to setup** | **Pros** | **Cons** | **How to setup** |
| ----- | ----- | ----- | ----- | ----- |
| Google Colab | Easy | Free to use, almost zero setup required, can share work with others as easy as a link | Doesn't save your data outputs, limited compute, subject to timeouts | [Follow the Google Colab Guide](https://colab.research.google.com/notebooks/gpu.ipynb) |
| Use your own | Medium | Run everything locally on your own machine | GPUs aren't free, require upfront cost | Follow the [PyTorch installation guidelines](https://pytorch.org/get-started/locally/) |
| Cloud computing (AWS, GCP, Azure) | Medium-Hard | Small upfront cost, access to almost infinite compute | Can get expensive if running continually, takes some time to setup right | Follow the [PyTorch installation guidelines](https://pytorch.org/get-started/cloud-partners/) |

There are more options for using GPUs but the above three will suffice for now.

Personally, I use a combination of Google Colab and my own personal computer for small scale experiments (and creating this course) and go to cloud resources when I need more compute power.

> **Resource:** If you're looking to purchase a GPU of your own but not sure what to get, [Tim Dettmers has an excellent guide](https://timdettmers.com/2020/09/07/which-gpu-for-deep-learning/).

To check if you've got access to a Nvidia GPU, you can run `!nvidia-smi` where the `!` (also called bang) means "run this on the command line".



In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


If you don't have a Nvidia GPU accessible, the above will output something like:

```
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.
```

In that case, go back up and follow the install steps.

If you do have a GPU, the line above will output something like:

```
Wed Jan 19 22:09:08 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 495.46       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   35C    P0    27W / 250W |      0MiB / 16280MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```



### 2. Getting PyTorch to run on the GPU

Once you've got a GPU ready to access, the next step is getting PyTorch to use for storing data (tensors) and computing on data (performing operations on tensors).

To do so, you can use the [`torch.cuda`](https://pytorch.org/docs/stable/cuda.html) package.

Rather than talk about it, let's try it out.

You can test if PyTorch has access to a GPU using [`torch.cuda.is_available()`](https://pytorch.org/docs/stable/generated/torch.cuda.is_available.html#torch.cuda.is_available).


In [ ]:
# Check for GPU
import torch
torch.cuda.is_available()

False

menggunakan modul torch untuk memeriksa ketersediaan GPU. Fungsi torch.cuda.is_available() mengembalikan nilai True jika GPU tersedia dan False jika tidak.

If the above outputs `True`, PyTorch can see and use the GPU, if it outputs `False`, it can't see the GPU and in that case, you'll have to go back through the installation steps.

Now, let's say you wanted to setup your code so it ran on CPU *or* the GPU if it was available.

That way, if you or someone decides to run your code, it'll work regardless of the computing device they're using.

Let's create a `device` variable to store what kind of device is available.

In [ ]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

mengatur variabel device berdasarkan ketersediaan GPU. Jika GPU tersedia, maka nilai device akan diatur menjadi "cuda" (mengindikasikan penggunaan GPU). Jika tidak, nilai device akan diatur menjadi "cpu" (mengindikasikan penggunaan CPU).



If the above output `"cuda"` it means we can set all of our PyTorch code to use the available CUDA device (a GPU) and if it output `"cpu"`, our PyTorch code will stick with the CPU.

> **Note:** In PyTorch, it's best practice to write [**device agnostic code**](https://pytorch.org/docs/master/notes/cuda.html#device-agnostic-code). This means code that'll run on CPU (always available) or GPU (if available).

If you want to do faster computing you can use a GPU but if you want to do *much* faster computing, you can use multiple GPUs.

You can count the number of GPUs PyTorch has access to using [`torch.cuda.device_count()`](https://pytorch.org/docs/stable/generated/torch.cuda.device_count.html#torch.cuda.device_count).

In [ ]:
# Count number of devices
torch.cuda.device_count()

0

Fungsi torch.cuda.device_count() digunakan untuk menghitung jumlah GPU yang tersedia pada sistem. Nilai yang dikembalikan akan menunjukkan berapa banyak GPU yang terpasang dan dapat diakses menggunakan PyTorch.



Knowing the number of GPUs PyTorch has access to is helpful incase you wanted to run a specific process on one GPU and another process on another (PyTorch also has features to let you run a process across *all* GPUs).

### 3. Putting tensors (and models) on the GPU

You can put tensors (and models, we'll see this later) on a specific device by calling [`to(device)`](https://pytorch.org/docs/stable/generated/torch.Tensor.to.html) on them. Where `device` is the target device you'd like the tensor (or model) to go to.

Why do this?

GPUs offer far faster numerical computing than CPUs do and if a GPU isn't available, because of our **device agnostic code** (see above), it'll run on the CPU.

> **Note:** Putting a tensor on GPU using `to(device)` (e.g. `some_tensor.to(device)`) returns a copy of that tensor, e.g. the same tensor will be on CPU and GPU. To overwrite tensors, reassign them:
>
> `some_tensor = some_tensor.to(device)`

Let's try creating a tensor and putting it on the GPU (if it's available).

In [ ]:
# Membuat tensor (default di CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor tidak berada di GPU
print(tensor, tensor.device)

# Memindahkan tensor ke GPU (jika tersedia)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu


tensor([1, 2, 3]) cpu


tensor([1, 2, 3])

mencantumkan tensor awal di CPU dan tensor setelah dipindahkan ke GPU (jika GPU tersedia). Jika GPU tidak tersedia, tensor tetap berada di CPU.

If you have a GPU available, the above code will output something like:

```
tensor([1, 2, 3]) cpu
tensor([1, 2, 3], device='cuda:0')
```

Notice the second tensor has `device='cuda:0'`, this means it's stored on the 0th GPU available (GPUs are 0 indexed, if two GPUs were available, they'd be `'cuda:0'` and `'cuda:1'` respectively, up to `'cuda:n'`).



### 4. Moving tensors back to the CPU

What if we wanted to move the tensor back to CPU?

For example, you'll want to do this if you want to interact with your tensors with NumPy (NumPy does not leverage the GPU).

Let's try using the [`torch.Tensor.numpy()`](https://pytorch.org/docs/stable/generated/torch.Tensor.numpy.html) method on our `tensor_on_gpu`.

In [ ]:
# Jika tensor berada di GPU
tensor_on_gpu = tensor.to(device)

# Mencoba mengonversi tensor di GPU menjadi NumPy (akan menghasilkan kesalahan)
tensor_on_gpu.numpy()


array([1, 2, 3])

gunakan .detach().cpu().numpy() untuk mengembalikan tensor ke CPU terlebih dahulu dan kemudian mengonversinya menjadi array NumPy.







Instead, to get a tensor back to CPU and usable with NumPy we can use [`Tensor.cpu()`](https://pytorch.org/docs/stable/generated/torch.Tensor.cpu.html).

This copies the tensor to CPU memory so it's usable with CPUs.

In [ ]:
# Mengembalikan tensor dari GPU ke CPU dan mengonversinya menjadi NumPy array
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu


array([1, 2, 3])

Dengan menggunakan .cpu().numpy(), Anda memindahkan tensor dari GPU ke CPU dan kemudian mengonversinya menjadi array NumPy. Hal ini memungkinkan operasi ini dilakukan dengan benar tanpa menghasilkan kesalahan.







The above returns a copy of the GPU tensor in CPU memory so the original tensor is still on GPU.

In [ ]:
tensor_on_gpu

tensor([1, 2, 3])

## Exercises

All of the exercises are focused on practicing the code above.

You should be able to complete them by referencing each section or by following the resource(s) linked.

**Resources:**

* [Exercise template notebook for 00](https://github.com/mrdbourke/pytorch-deep-learning/blob/main/extras/exercises/00_pytorch_fundamentals_exercises.ipynb).
* [Example solutions notebook for 00](https://github.com/mrdbourke/pytorch-deep-learning/blob/main/extras/solutions/00_pytorch_fundamentals_exercise_solutions.ipynb) (try the exercises *before* looking at this).

1. Documentation reading - A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness). See the documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor) and for [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).
2. Create a random tensor with shape `(7, 7)`.
3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).
4. Set the random seed to `0` and do exercises 2 & 3 over again.
5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one). If there is, set the GPU random seed to `1234`.
6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed).
7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).
8. Find the maximum and minimum values of the output of 7.
9. Find the maximum and minimum index values of the output of 7.
10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

## Extra-curriculum

* Spend 1-hour going through the [PyTorch basics tutorial](https://pytorch.org/tutorials/beginner/basics/intro.html) (I'd recommend the [Quickstart](https://pytorch.org/tutorials/beginner/basics/quickstart_tutorial.html) and [Tensors](https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html) sections).
* To learn more on how a tensor can represent data, see this video: [What's a tensor?](https://youtu.be/f5liqUk0ZTw)